### ISSUE TITLE
Barang player bisa di ambil

### ISSUE THREAD

**Issue by leonidesu** [leonidesu/AzN-Survival2#10]
Gw buka inventory (Pencet E) trus gw klik kiri di item (contoh : sword)
(Kayak mau drop barang, tapi ga ngedrop)
trus Haruna kill gw, dan semua item gw ke drop, tapi sword itu bisa diambil sama Haruna, sedangkan item lain gabisa diambil.

**Comment by Andika30** [comment]
Judulnya seharusnya itu "Barang Player Bisa Diambil" karna kan seharusnya sword itu gabisa diambil sama player lain, kan ada LockDropsnya, tapi di bug ini, swordnya bisa keambil sama player. 

Gw pertegas :
Jadi gini, gw buka inventory minecraft, trus gw klik kiri di swordnya, swordnya kan 'melayang', nah pas itu gw di kill sama orang, otomatis barang gw drop semua, seharusnya barang gw itu semuanya gabisa diambil sama orang, tapi orang itu bisa ambil sword gw, sedangkan barang lain masih aman (gabisa diambil sama orang lain)

**Comment by leonidesu** [comment]
@Andika30 Dalam hal ini keep inventory memang sengaja di matikan dan barang yang terjatuh **memang bisa** di ambil oleh siapa saja apabila tidak membawa chest dan sign (Cenotaph). Bug ini terlihat kurang tepat karena konsep yang kita bicarakan sangat berbeda.

**Comment by Andika30** [comment]
bukannya kalo gw mati di kill orang itemnya ke drop tapi item gw gabisa diambil sama player lain ya?
Kecuali gw /UnlockDrops baru orang lain bisa ambil item gw yang drop kan?
