### ISSUE TITLE
Cenotaph tidak jalan saat mati di atas farmland

### ISSUE THREAD

**Issue by leonidesu** [leonidesu/AzN-Survival2#19]

**Comment by Arthzalcotl** [comment]
Gw tadi abis mati di reso sekitar jam 23:14-23:16, gw lg didalam gua dan berdiri diatas stone, cenotaph ga jalan.
Gw bawa 2 chest dan 3 sign.

Ada perlu sesuatu lagi kah selain itu? Karena di tutorial cuma disuruh bawa "chest" dan "2 sign".

**Comment by leonidesu** [comment]
Cenotaph telah di gantikan oleh sistem Shard. Mohon laporkan lagi apabila masih terdapat kendala.
