### ISSUE TITLE
Grief Prevention stick claim

### ISSUE THREAD

**Issue by leonidesu** [leonidesu/AzN-Survival2#22]
Gp bisa di claim dengan stick

**Comment by leonidesu** [comment]
Tidak terbukti bahwa claim bisa dilakukan dengan stick. Harap berikan keterangan tambahan dalam waktu 3 hari kedepan. Bila tidak ada respon, maka issue ini akan ditutup.

**Comment by Historia333** [comment]
Stick itu kegunaanya hanya untuk mengecek claim atau di sebut dalam GP tersebut "Inspection tools" jadi tidak ada cara apapun untuk claim lahan selain chest dan wooden shovel.

End of case, closed.
