### ISSUE TITLE
Tambahkan permission untuk /mcability

### ISSUE THREAD

**Issue by leonidesu** [leonidesu/AzN-Survival2#33]

**Comment by EP2598** [comment]
Player tidak memiliki permission untuk disable mcability (/mcability). Harap ditambahkan agar player dapat disable mcability.

**Comment by Historia333** [comment]
@EP2598 Dalam tahap Alpha Test 1 ini fitur McMMo masih non aktif. Akan tetapi kedepannya akan di tambahkan

**Comment by leonidesu** [comment]
@EP2598 Maksudnya mcability masih bisa di akses ya sekarang?
