### ISSUE TITLE
Cenotaph gak work diatas chest(Maybe other "non full block" block

### ISSUE THREAD

**Issue by NotVB** [leonidesu/AzN-Survival2#40]
**Deskripsi Bug**
Pas aku sekarat, aku /back, terus, balik nya diatas chest. Nah, aku kan mati diatas chest, terus pas aku /back buat ambil cenotaph, bukan drop. IT'S FVCKING GONE. What about my stuff? THEY ALL ARE GONE. WTF MINECRAFT, DO SOMETHING GOOD FOR ONCE

**Cara menghasilkan bug**
Mati di atas chest

**Hal yang seharusnya terjadi**
Cenotaph tetep muncul

**Catatan tambahan**
Keknya bug ini terjadi kalau mati di semua block yang gak full block (chest, soulsand, trapdoor, halfslab, stair, dll)

**Catatan tambahan lagi**
Can I get my stuff back? I only need my fishing rod(UB 3 Lure 3). I rage-quited early on this day

**Comment by leonidesu** [comment]
Saat ini Cenotaph telah di gantikan oleh sistem Shard. Apabila tidak ingin inventory drop, bawalah 1 Shard di Inventory.
