### ISSUE TITLE
Barang player bisa di ambil saat mati

### ISSUE THREAD

**Issue by leonidesu** [leonidesu/AzN-Survival2#9]
Barang player pas mati bisa diambil

Contoh : gw ada 1 bone, haruna ada 1 bone juga

Gw kill haruna, invent dia drop, dan gabisa gw ambil karna dia ga /UnlockDrops

Trus gw coba drop bone gw, kan haruna punya bone, nyatu jd satu (kecampur) ternyata bisa gw ambil dan bone dia keambil sama gw

**Comment by Andika30** [comment]
more Info : Gw punya 2 bone, orang itu punya 1 bone.
Trus gw kill orang itu, semua itemnya ke drop dan gw gabisa ambil.
Gw coba drop 1 bone punya gw ke bone orang itu yg ke drop, sehingga bone itu nyatu (gabung), dan ternyata bone yg udh nyatu (punya gw dan punya orang itu) bisa gw ambil dua-duanya. Sehingga bone dia yang harusnya gabisa diambil sama gw, jadi bisa keambil

**Comment by leonidesu** [comment]
Duplicate of #10

**Comment by leonidesu** [comment]
Semua inventory yang drop tanpa adanya cenotaph **BISA** di ambil oleh siapapun.
